misc: Fix PostmarketOS apk build
This file is necessary to make the PostmarketOS APKBUILD work without an error.

Otherwise the build fails with this error:

./tools/include/uapi/linux/types.h:5:10: fatal error: 'asm-generic/int-ll64.h' file not found
    5 | #include <asm-generic/int-ll64.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~

The reason of the failed build is unknown, maybe a PostmarketOS quirk?